-- GameDeck no longer uses a one-shot bootstrap schema.
--
-- This file previously granted anonymous read access to the personal library.
-- It is intentionally non-executable so it cannot recreate that retired
-- security model in a new environment.
--
-- The versioned files in ./migrations are the source of truth. See README.md
-- in this directory for the safe deployment and verification procedure.
